### ISSUE TITLE
メアドログイン時のニコニコのログイン履歴に関して

### ISSUE THREAD

**Issue by lisa1925** [raccy/obs-rtmp-nicolive#10]
ログイン履歴を見た際に判明
https://account.nicovideo.jp/my/history/login
接続元 : ブラウザ が1分間の間に複数ある。
「自動で配信開始と枠移動を行う」を利用すると流れるのですが、これは仕様ですか？
気にしなければ問題はないですが、ログイン履歴が大量にあるので…。

ニコニコ設定
2段階認証を利用 (利用しない場合も発生する)

発生手順
OBS Studioを起動
メールアドレスログインをする
自動で配信開始と枠移動を行う を利用する (監視時間 10秒)

発生頻度
OBS Studioを終了するまでの間

発生しない手段
クッキーのユーザーセッションを利用

ほぼ発生しない手段
自動で配信開始と枠移動を行うを利用しない (履歴は起動時と配信開始時のみ発生)

**Comment by raccy** [comment]
メアドログインはNiconico Live Encoderと同じ方法を使っています。Niconico Live Encoderでも同じように履歴が出るのであれば、たぶんニコニコ動画側の仕様です。出なければ…うーん、何かが違うのでしょう。

**Comment by lisa1925** [comment]
NLEをインストールして試してみました。
ログイン時と配信開始を押した際には履歴が出ました。
それ以外は出ていないようなので、多分このプラグインの自動監視の際にアクセスがあってそれが表示されてるのかもです…
ニコニコ動画側の仕様っぽいような気がしたので、もう少し様子見て変わらなければこのIssuesは閉じさせて頂きますー。
返信ありがとうございました！
