### ISSUE TITLE
予約枠がある際の動作に関して

### ISSUE THREAD

**Issue by lisa1925** [raccy/obs-rtmp-nicolive#12]
予約枠を試しに取った際に気づいたので、報告させて頂きます。

バグ発生手順 
1、OBS Studio にプラグイン導入 (手動 or ビルド)
2、ログインを済ませる (セッション接続・Viqo含む)
3、自動で配信開始と枠移動を行うにチェックを入れる (監視時間 10秒)
4、予約枠を取得 or 取得済み
5、予約枠開始前なのに、予約枠に接続されて配信中になる。

バグ発生時のAPI
予約枠を取得すると、下記APIに枠情報が反映されている。
http://live.nicovideo.jp/api/getpublishstatus?v=
枠情報が反映された状態で、枠を取得するとそちらが反映される。(予約枠前に)
start_timeがbase_time/open_timeより遅かったので、そちらを読み込めば良いかもしれません。(憶測)

フォークして修正及び改変をしている所 (参考になるか分からないですが)
http://variedtastefinder.jp:3000/root/rtmp-nicolive

よろしくお願い致します。

**Comment by raccy** [comment]
v2.1.0-preで開始時刻(start_time)と終了時刻(end_time)を見て、放送開始するかを判断するようにしてみました。お試しください。

**Comment by lisa1925** [comment]
予約枠が取得出来たら試してみます。
またその際にご報告します。

あ、ちなみに今の所「v2.1.0-pre」では配信枠を取った際のテスト時間では自動開始されなかったので多分大丈夫だと思ってます。

**Comment by lisa1925** [comment]
チケットが手に入ったので予約枠を取得して検証してみました。
この報告した問題はばっちり解決していました。
修正して頂きありがとうございます。

この変更によって、枠のテスト時間では自動開始されなくなってたのが個人的に嬉しいです。
本番開始をしてから自動開始の動作していたので、良い挙動だなーと思いました。
