### ISSUE TITLE
新配信（β）の getpublishstatus からの rtmpurl 取得について

### ISSUE THREAD

**Issue by shousa** [raccy/obs-rtmp-nicolive#16]

**Comment by shousa** [comment]
新配信（β）での getpublishstatus での設定内容を確認しました。
新配信（β）では、従来の配信と設定内容に仕様の変更があるようで、
現在配布されているプラグインでは配信できません。
新仕様に対応する場合は、以下のタグから値を取得可能です。

<url> タグの値を、そのまま「URL」に設定可能
<stream> タグの値を、そのまま「ストリームキー」に設定可能
<ticket/> 設定されていなかったため、おそらく不使用と思われる
<bitrate>1000</bitrate> ビットレート合計の上限値の設定があるのは従来通り

**Comment by lisa1925** [comment]
まだ枠数に制限がある為、比較になれば。(一部隠しています)
ニコニコ生放送「新配信（β）」の提供を開始しました‐ニコニコインフォ
http://blog.nicovideo.jp/niconews/ni064355.html

旧仕様 getpublishstatus
https://pbs.twimg.com/media/CwL8GtSVUAEKTkU.png
新仕様 getpublishstatus
https://pbs.twimg.com/media/CwL8HJQUsAI-Dyj.png
