### ISSUE TITLE
v2.1.0 の必須ランタイムに関して

### ISSUE THREAD

**Issue by style1925** [raccy/obs-rtmp-nicolive#19]
v2.1.0よりVS2015に変更された影響で「Visual Studio 2015 の Visual C++ 再頒布可能パッケージ」がないと起動時にエラーが出ます。
エラーが出る為、プラグインを導入出来ていても表示されません。
インストール方法、リリースページ、README.mdにインストールする事を明記して下さい。
よろしくお願いします。

記載例
Windows環境の方へ
v2.1.0からは「[Visual Studio 2015 の Visual C++ 再頒布可能パッケージ](http://www.microsoft.com/ja-JP/download/details.aspx?id=48145)」が必須となります。
32bit環境 「vc_redist.x86.exe」を入手してインストールして下さい。
64bit環境 「vc_redist.x86.exe」「vc_redist.x64.exe」を入手してインストールして下さい。

**Comment by raccy** [comment]
あ…VS2015でコンパイルしたんだった…

**Comment by style1925** [comment]
インストールしてない環境で起動した時にエラーが出て気づきましたｗ
お手数をおかけしますが、よろしくお願い致します。

**Comment by raccy** [comment]
ダウンロードの所に注意書きを追加しました。また、再配布DLLを付属したバージョン(**動作未確認**)をつけました。

次からはVC2015オンリーにしたいんですが、Win向けバイナリパッケージはちょっと考慮が必要かな。

**Comment by style1925** [comment]
注意書きありがとうございます。
再配布付属のやつは試せたら試してみます。
