### ISSUE TITLE
v1.0ではWindows環境でのCmakeでエラー発生

### ISSUE THREAD

**Issue by shousa** [raccy/obs-rtmp-nicolive#2]
CMake Error at plugins/rtmp-nicolive/CMakeLists.txt:24 (add_library):
  add_library cannot create imported target "libobs" because another target
  with the same name already exists.

v1.0のwindows環境でのビルドを実施してみたところ、
上記のメッセージのエラーが発生してcmakeで失敗しました。
v0.4.1の頃のcmakeでは特に問題なくビルド出来ていました。
CMakeLists.txtを見たところ、その下の部分もMac環境依存っぽい記述がありそうです。

**Comment by shousa** [comment]
追加の確認結果です。
obs-studio 0.7.3 と obs-rtmp-nicolive v0.5 の組み合わせでは、正常にビルド可能
obs-studio 0.8.2 と obs-rtmp-nicolive c2b5635 の組み合わせでは、正常にビルド可能
CMakeLists.txt の変更前までのバージョンではおそらく大丈夫だと思われます。

**Comment by raccy** [comment]
OBSと一緒にコンパイルしたときと分けてコンパイルしたときで条件分けを追加してます。
ただ、一緒なら以前と一緒になるはずなんですけど…。
WinでもわけてコンパイルできるようにCMakeLists.txtを書き換え中なので、
それが対応できればうまく動くんじゃ無いかなと思っています。
(Mac環境依存部分は・・・とりあえずの実装だったのでWinならMacならで分かれる予定です)
ただ、問題多いなら、CMakeLists.txtを切り替えて使ってねにしようかと思ってます。

**Comment by raccy** [comment]
CMakeでの分岐方法を変えました。いまのmasterなら、うまくいくはずです。
一度試してみて下さい。
Winでもなんとか単独ビルドできそうなんですが、obs-studio本家が5.4.1のスナップショット版Qtを使っているらしく、リンクが…リンクが…リンクが…orz
dll単独だと簡単にリンクできないWindowsを捨てたい。マジで捨てたい。

**Comment by shousa** [comment]
Windows版に関して、特に問題なくビルド出来たようです。
e3265abのコミットにもタグ付けして頂けるとありがたいです。
また、Windows版のプラグインの配布バイナリは、
0.8.2、0.8.3(2/21公開）ともに動作確認大丈夫でした。

**Comment by raccy** [comment]
対応済み1.1リリース
