### ISSUE TITLE
v2.1.0 以降の自動調整に関して

### ISSUE THREAD

**Issue by style1925** [raccy/obs-rtmp-nicolive#20]
音質重視したい人には、嬉しいバグですが気になるので報告します。
以前(v2.0)までは、一定音質(192kbps？)以上は設定出来ませんでしたが設定が出来るようです。
映像へのビットレート調整は大丈夫なので、このままの仕様でも大丈夫かもですが。

バグ発生環境
Windows 8.1 Pro 64bit / OS X El Capitan 10.11
OBS Studio 0.16.5 (公式バイナリ) / OBS Studio 0.16.2 (公式バイナリ)
obs-rtmp-nicolive v2.1.0

バグを回避する方法
1、このプラグインを使用しない

映像ビットレートの最低値に関して (フォームで変更出来る値)
基本モード : 200kbps
詳細モード : 50kbps

バグ発生設定 (基本モードの場合)
1、「映像ビットレートを自動調整」はON
2、映像ビットレートは200kbps設定・音声ビットレートは320kbps設定
(この際に、出力に警告が出る。)
警告: 配信の映像ビットレートは 160 に設定され、これは現在の配信サービスの上限です。 160 より大きい値に設定する場合、高度なエンコーダオプションを有効にして「配信サービスのビットレートを制限する」のチェックをオフにしてください。

ログ (基本モード 音声320kbps設定　映像が160kbpsに下げられる)
15:19:39.358: [x264 encoder: 'simple_h264_stream'] preset: veryfast
15:19:39.359: [x264 encoder: 'simple_h264_stream'] settings:
15:19:39.359: 	rate_control: CBR
15:19:39.359: 	bitrate:      160
15:19:39.359: 	buffer size:  160
15:19:39.359: 	crf:          0
15:19:39.359: 	fps_num:      30
15:19:39.359: 	fps_den:      1
15:19:39.359: 	width:        1280
15:19:39.359: 	height:       720
15:19:39.359: 	keyint:       250
15:19:39.359: 	vfr:          off
15:19:39.359: 
15:19:39.368: [CoreAudio AAC: 'simple_aac']: settings:
15:19:39.368: 	mode:          AAC
15:19:39.368: 	bitrate:       320
15:19:39.368: 	sample rate:   44100
15:19:39.368: 	cbr:           on
15:19:39.368: 	output buffer: 1536

バグ発生設定 (詳細モードの場合)
1、「映像ビットレートを自動調整」はON
2、映像ビットレートは50kbps設定・音声ビットレートは320kbps設定

ログ (基本モード 320kbps設定　映像が160kbpsに上げられる)
15:23:30.368: [x264 encoder: 'streaming_h264'] preset: veryfast
15:23:30.368: [x264 encoder: 'streaming_h264'] settings:
15:23:30.368: 	rate_control: CBR
15:23:30.368: 	bitrate:      160
15:23:30.368: 	buffer size:  160
15:23:30.368: 	crf:          0
15:23:30.368: 	fps_num:      30
15:23:30.368: 	fps_den:      1
15:23:30.368: 	width:        1280
15:23:30.368: 	height:       720
15:23:30.368: 	keyint:       250
15:23:30.368: 	vfr:          off
15:23:30.368: 
15:23:30.375: [CoreAudio AAC: 'Track1']: settings:
15:23:30.375: 	mode:          AAC
15:23:30.375: 	bitrate:       320
15:23:30.375: 	sample rate:   44100
15:23:30.375: 	cbr:           on
15:23:30.375: 	output buffer: 1536

**Comment by raccy** [comment]
もともと「基本モード」しか想定していなかったため、ビデオビットレートの最低値を200kbpsにしていました。「詳細モード」への対応と詳細の確認で200kbpsを下回ることがわかったので、最低値を0より大きいに変更しています。

ビデオビットレートがどこまで下がっても大丈夫なのかは試していないですが、なんとなく、大丈夫そうですので、今の仕様で行きたいと思います。

**Comment by style1925** [comment]
あ、詳細モード対応で変更されていたんですね。
今の仕様に変更された事で、制限がなくなったので良いと思います！
(今までだと音質重視に出来ない事で困ってる音質厨の人が居たので…笑)
教えて頂きありがとうございました。
