### ISSUE TITLE
OBS Studio 18.x以降のニコ生プラグイン動作に関して

### ISSUE THREAD

**Issue by style1925** [raccy/obs-rtmp-nicolive#24]
環境
OBS Studio 18.x以降
ニコ生プラグイン v2.1.0

OBS Studio 18.x以降に放送枠がない状態時に、OBS Studioの配信開始ボタンを押すとニコ生プラグインのエラー(*1)の後にOBS Studio側のエラー(*2)が発生するようになりました。

今まで通りのニコ生プラグインのエラー (*1)
![default](https://cloud.githubusercontent.com/assets/1337354/24403232/de64cf86-13f6-11e7-81fb-255c840e33cf.png)

新たに発生するようになったエラー (*2)
![c43c86185e9345b7702be4ba27d3730683cd1052](https://cloud.githubusercontent.com/assets/1337354/24403193/b8070b9c-13f6-11e7-8077-c030756d9577.png)

発生時の様子 (動画)
https://youtu.be/w8WGBVuNUGg

このエラーは下記コミットの実装で出るようになりました。
https://github.com/jp9000/obs-studio/commit/6bc1ecc794015af3984f4e4315b558f3445b5416
エラーを条件で出る、出ないという感じには出来ないでしょうか。
よろしくお願い致します。

放送枠がない時に配信開始を押す(設定が正常)　→　(*2)エラーを出さずに、(*1)エラーのみ。(※18.0未満での動作)

現状の動作で大丈夫な部分
放送枠がない時に放送開始を押す(設定が不適切)　→　(*2)エラーを出す。(動画と同じ感じに)
配信枠がある時に放送開始を押す(設定が不適切)　→　(*2)エラーを出す。(これは正常動作)

**Comment by raccy** [comment]
配信できそうなら`true`、できないなら`false`という選択しか無く、OBS側が出力するメッセージは抑止できません。
プラグイン側のメッセージを出さないと言うぐらいしかないのかなーと思っています。開発版でこっそり修正しています。

**Comment by style1925** [comment]
なるほど…。
開発版での修正ありがとうございます。

**Comment by style1925** [comment]
v2.2.0-pre1 でポップアップメッセージが変わったのでこの問題はクローズ。
