### ISSUE TITLE
Microsoft Visual C++ 2015 再頒布可能パッケージ Update 3のリンク先に関して

### ISSUE THREAD

**Issue by style1925** [raccy/obs-rtmp-nicolive#29]
v2.1.0に記載しているリンク先ページが終了？しているようです。
現時点では下記URL先から入手が出来るようなので、URLを更新して頂けますか？
https://www.microsoft.com/ja-jp/download/details.aspx?id=52685

**Comment by raccy** [comment]
今見たらリンク先にアクセスできるようです。

**Comment by style1925** [comment]
あ、アクセス出来るようになってますね…。
このIssuesはCloseします。
