### ISSUE TITLE
linux版obs-studioでニコ生アカウントを打ち込み適用すると強制終了してしまう

### ISSUE THREAD

**Issue by smallboy67rt** [raccy/obs-rtmp-nicolive#5]
sudo apt-get install build-essential pkg-config cmake git checkinstall libx11-dev libgl1-mesa-dev libpulse-dev libxcomposite-dev libxinerama-dev libv4l-dev libudev-dev libfreetype6-dev libfontconfig-dev qtbase5-dev libqt5x11extras5-dev libx264-dev libxcb-xinerama0-dev libxcb-shm0-dev libjack-jackd2-dev libcurl4-openssl-dev libavcodec-dev libavfilter-dev libavdevice-dev libfdk-aac-dev zlib1g-dev yasm qtbase5-dev
で環境を整えた後obsマニュアル通りにgitからffmpegをインストールしました
そしてlinux版のobs-studio0.11.1のソースファイルをダウンロードしマニュアル通りobs-rtmp-nicoliveのディレクトリ名をobs-rtmp-nicoliveに変更
obsの/plugins/CMakeLists.txtの最後列へadd_subdirectory(rtmp-nicolive)
そしてobsソースのトップから
mkdir build
cd build
cmake -DUNIX_STRUCTURE=1 -DCMAKE_INSTALL_PREFIX=/usr ..
make -j4
sudo checkinstall --pkgname=obs-studio --fstrans=no --backup=no --pkgversion="$(date +%Y%m%d)-git" --deldoc=yes
でインストールは正常終了し起動もするようになりましたがobsの設定→配信→配信種別　ニコニコ生放送→メールアドレスタブへニコニコ動画の登録メールアドレス　パスワードタブへニコニコ動画の登録パスワード
を打ち込み適用及びOKした所強制クラッシュが発生しました

またブラウザのセッションクッキー、Viqoの設定から読み込むも試しましたが結果は同じものでした

obsの最新版である0.12.4でも一括ビルド出来タブに表示されましたが同操作で強制クラッシュでした

**Comment by raccy** [comment]
手元に実行環境がないので試せていないのですが、クラッシュ直前のターミナルログや`~/.obs-studio/logs`にあるログで落ちる直前のがあれば何かわかるかも知れません。また、Debugでコンパイルすると詳細なログがでるので可能であればそちらで試して欲しいです。

なお、Debugログでは**ログイン時のユーザ名やパスワード、クッキーセッション等が平文で表示されます**ので、絶対にそのまま貼り付けないようにお願いします。

**Comment by smallboy67rt** [comment]
#3でのFindLibcurl.cmakeを含まないビルドを行っていたせいで起きた現象だったようです

obs単体をソースからインストールしFindLibcurl.cmakeを含んだobs-rtmp-nicoliveを単体でビルドし組み込んだ所ニコニコ生放送へ切り替えユーザーとパスワードを打ち込み適用させてもクラッシュしなくなりました

またviqoの方と連携させても落ちなくなったので明日には動作チェックを行い問題なければcloseさせていただきます

ありがとうございました
