### ISSUE TITLE
遅延配信を設定した際の動作に関して

### ISSUE THREAD

**Issue by style1925** [raccy/obs-rtmp-nicolive#9]
詳細設定の遅延配信を試した所、動作がおかしいようなので報告させて頂きます。

発生環境
OBS Studio 0.12.0以降 (動作テストにて判明)
※バグの発見は0.14.2使用時

バグ発生手順
1、OBS Studio にプラグイン導入 (手動 or ビルド)
2、ログインを済ませる
3、詳細設定 > 遅延配信 を有効にする
4、自動で配信開始と枠移動を行うにチェックを入れる (監視時間 10秒)
5、放送枠を取得する
6、配信枠が検出され自動開始された際に▼が押された状態になる
(バグの様子 : https://gyazo.com/2d124bc77b8f7dab6aba5bdd2403fe8d )
7、OBS Studioのウィンドウをクリックすると遅延停止までの時間が動作する
※手動で開始及び、自動で配信開始と枠移動をしない場合は発生しません。
※遅延配信設定は0.12.0より追加された為 0.11.4 では発生しない
※0.16.0以降はAPIが追加？
https://github.com/jp9000/obs-studio/tree/master/UI/obs-frontend-api

修正が可能でしたら、よろしくお願い致します。

**Comment by raccy** [comment]
「遅延配信」は試してないのでそこら辺の不具合かなと。
自動開始時の方法を変える予定ですので、それでどうなるかは見ていきたいと思います。

**Comment by lisa1925** [comment]
https://github.com/raccy/obs-rtmp-nicolive/blob/master/doc/TODO.md
「配信開始をGUIのイベント叩きじゃ無くて、ショートカット関係のを使う。」って所ですか？
それで改善される事を期待しています。
返信ありがとうございます！

**Comment by style1925** [comment]
v2.1.0-preにて、ショートカットAPI？に変更されたのでこの問題は発生しなくなりました。
解決したので、このIssuesをCloseします。
